packaging: partially revert #5604, stay on focal to use libssl1.1. Add libssl explicitly.
Trying to run the image while debugging:  https://github.com/hasura/graphql-engine-mono/pull/6172/ I get:

    $ docker run -it hasura/graphql-engine:dev-b91a92b-jberrymanalexghc92-ci-REBASE10-cherry-.ubuntu.amd64
    graphql-engine: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

It seems as though the ubuntu image has been broken in some way since
moving to jammy (Which only ships with `libssl.3`), but strangely this
only shows up on main, not in PRs (except on the 9.2 branch…?)

we use this in tests for instance: .buildkite/scripts/test-dc-sdk.sh

Strangely I don't get the error with an image from recent PRs:
https://github.com/hasura/graphql-engine-mono/pull/6148
https://github.com/hasura/graphql-engine-mono/pull/6156 (to latest release)

...although Samir sees it on some he looked at

```
docker run -it hasura/graphql-engine:dev-46eaa39-plcreleasev2.13bq-scalars.ubuntu.amd64 graphql-engine version
Fatal Error: Either of --metadata-database-url or --database-url option expected
```

PR-URL: https://github.com/hasura/graphql-engine-mono/pull/6176
Co-authored-by: Samir Talwar <47582+SamirTalwar@users.noreply.github.com>
GitOrigin-RevId: 6eea65f2d1dc7f0d13bcd58f94737810d290cb89