Convert types to use OpenDd trait for deserialization, fix bugs in trait macro (#1758)
### What
This PR converts `ModelPredicate` and related OpenDD types to be
deserialized via the OpenDD trait rather than by serde. This sets us up
to be able to use the Spanned type to capture JSON paths for contextual
error printing.

However, doing so uncovered the fact that the macro that generates the
deserialization logic for externally tagged enums only supports having
objects as the variants. Whereas `ModelPredicate::And` etc contain an
array, not an object.

It also uncovered a bug in OpenDd trait JSON schema generation that
resulted in infinite loops when using recursive types (which
`ModelPredicate` is).

AND... 😫 it also found a bug in the the JSON path tracking code where
externally tagged enums didn't have their external tag included in the
json path.

ALSO: Spanned was incorrectly causing OpenDD types to be inlined and
repeated in the JSON schema.

All these problems have been fixed.

### How

The OpenDd macro code has been updated to fix the issues with
deserialization. When using external tagging, the tagged value now can
be anything and isn't forced to be an object. The deserialization also
uses the correct function that takes into account the tag property name
in the json path.

Here's the diff of the generated OpenDd macro code:

```diff
 impl open_dds::traits::OpenDd for ModelPredicate {
     fn deserialize(
         json: serde_json::Value,
         path: jsonpath::JSONPath,
     ) -> Result<Self, open_dds::traits::OpenDdDeserializeError> {
         let mut __object_map = match json {
             serde_json::Value::Object(map) => map,
             _ => {
                 return Err(open_dds::traits::OpenDdDeserializeError {
                     error: serde::de::Error::invalid_type(
                         serde::de::Unexpected::Other("not an object"),
                         &"object",
                     ),
                     path: jsonpath::JSONPath::new(),
                 })
             }
         };
         let mut __object_map_iter = __object_map.into_iter();
-        let(__tag_value_string,__inner) = __object_map_iter.next().ok_or_else(||open_dds::traits::OpenDdDeserializeError {
+        let(__tag_value_string,__tag_value) = __object_map_iter.next().ok_or_else(||open_dds::traits::OpenDdDeserializeError {
             error:serde::de::Error::invalid_type(serde::de::Unexpected::Other("found empty object"), &"object with only one of the following properties: fieldComparison, fieldIsNull, relationship, and, or, not",),path:jsonpath::JSONPath::new(),
         })? ;
         if let Some(_) = __object_map_iter.next() {
             return Err(open_dds::traits::OpenDdDeserializeError {
                 error:serde::de::Error::invalid_type(serde::de::Unexpected::Other("found multiple object properties"), &"object with only one of the following properties: fieldComparison, fieldIsNull, relationship, and, or, not",),path:jsonpath::JSONPath::new(),
             });
         }
         let __tag_value_str = __tag_value_string.as_str();
-        let mut __object_map = match __inner {
-            serde_json::Value::Object(map) => map,
-            _ => {
-                return Err(open_dds::traits::OpenDdDeserializeError {
-                    error: serde::de::Error::invalid_type(
-                        serde::de::Unexpected::Other("not an object"),
-                        &"object",
-                    ),
-                    path: jsonpath::JSONPath::new_key(__tag_value_str),
-                })
-            }
-        };
         match __tag_value_str {
-            "fieldComparison" => Ok(Self::FieldComparison(
-                open_dds::traits::OpenDd::deserialize(
-                    serde_json::Value::Object(__object_map),
-                    path,
-                )?,
-            )),
-            "fieldIsNull" => Ok(Self::FieldIsNull(open_dds::traits::OpenDd::deserialize(
-                serde_json::Value::Object(__object_map),
+            "fieldComparison" => Ok(Self::FieldComparison(open_dds::traits::deserialize_key(
+                __tag_value,
+                path,
+                __tag_value_string,
+            )?)),
+            "fieldIsNull" => Ok(Self::FieldIsNull(open_dds::traits::deserialize_key(
+                __tag_value,
                 path,
+                __tag_value_string,
             )?)),
-            "relationship" => Ok(Self::Relationship(open_dds::traits::OpenDd::deserialize(
-                serde_json::Value::Object(__object_map),
+            "relationship" => Ok(Self::Relationship(open_dds::traits::deserialize_key(
+                __tag_value,
                 path,
+                __tag_value_string,
             )?)),
-            "and" => Ok(Self::And(open_dds::traits::OpenDd::deserialize(
-                serde_json::Value::Object(__object_map),
+            "and" => Ok(Self::And(open_dds::traits::deserialize_key(
+                __tag_value,
                 path,
+                __tag_value_string,
             )?)),
-            "or" => Ok(Self::Or(open_dds::traits::OpenDd::deserialize(
-                serde_json::Value::Object(__object_map),
+            "or" => Ok(Self::Or(open_dds::traits::deserialize_key(
+                __tag_value,
                 path,
+                __tag_value_string,
             )?)),
-            "not" => Ok(Self::Not(open_dds::traits::OpenDd::deserialize(
-                serde_json::Value::Object(__object_map),
+            "not" => Ok(Self::Not(open_dds::traits::deserialize_key(
+                __tag_value,
                 path,
+                __tag_value_string,
             )?)),
             __ver => Err(open_dds::traits::OpenDdDeserializeError {
                 error: serde::de::Error::unknown_variant(
                     __ver,
                     &["fieldComparison, fieldIsNull, relationship, and, or, not"],
                 ),
                 path: jsonpath::JSONPath::new(),
             }),
         }
     }
```

The infinite recursion bug was fixed with a tweak in the OpenDd trait
implementation for Box.

V3_GIT_ORIGIN_REV_ID: 0ed6a63c519f99f9ec32e27fbb1f6758ee29d511